# Generated by Django 5.2.7 on 2025-10-20 08:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('notes', 'Notes/Document'), ('presentation', 'Presentation'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='course_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt', 'ppt', 'pptx', 'mp4', 'avi', 'mov', 'wmv', 'mkv', 'webm'])])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or external video URL', null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 15:30', max_length=20, null=True)),
                ('transcript', models.TextField(blank=True, help_text='Transcript for videos', null=True)),
                ('alt_description', models.TextField(blank=True, help_text='Alternative description', null=True)),
                ('file_size', models.CharField(blank=True, help_text='e.g., 2.5 MB', max_length=50, null=True)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'order', '-created_at'],
            },
        ),
    ]
