# Generated by Django 5.2.7 on 2025-10-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='has_sign_language',
            field=models.BooleanField(default=False, help_text='Check if sign language interpretation is available'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='sign_language_video_url',
            field=models.URLField(blank=True, help_text='Sign language interpretation video URL', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_sign_language',
            field=models.BooleanField(default=False, help_text='Check if sign language interpretation is available'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sign_language_video_url',
            field=models.URLField(blank=True, help_text='Sign language interpretation video URL (YouTube/Vimeo)', null=True),
        ),
    ]
