# Generated by Django 5.2.8 on 2025-11-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_coursematerial_has_sign_language_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
