# Generated by Django 5.2.8 on 2025-11-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_coursematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductreport',
            name='course',
        ),
        migrations.RemoveField(
            model_name='conductreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='conductreport',
            name='student',
        ),
        migrations.DeleteModel(
            name='ComplianceReport',
        ),
        migrations.DeleteModel(
            name='ConductReport',
        ),
    ]
